# Generated by Django 6.0.2 on 2026-02-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quartos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_check_in', models.DateField()),
                ('data_check_out', models.DateField()),
                ('valor_reserva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('F', 'Finalizada')], default='Pendente', max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.quarto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
    ]
